language: java
jdk:
- oraclejdk8
script: "./build.sh"
env:
- BUILD_LABEL=3.0.${TRAVIS_BUILD_NUMBER}
before_deploy:
  - "./deploy.sh"
  - nvm install v7.8.0
  - nvm use v7.8.0
  - npm install yarn
  - "./docs/deploy.sh"
deploy:
- provider: releases
  api_key:
    secure: C+vg/B+z+fqEtWh80ovIRruknQgG1sL/OaM5E4xhy589uGi6MDHrAZS9YuZ5ViQFjfCGGo+XzS8Up86yYPMTr1F+kRTViO/pGZst1yA8xO5o7Ep1Xd+q2mItpAhGMPJU0q41G9gIg0epF0OyIuYeXcAXo5h0LsNBS6PAQQEfpJQ=
  file:
  - "./fetch/target/s3fetch-assembly-${TRAVIS_TAG}.jar"
  - "./publish/target/s3publish-assembly-${TRAVIS_TAG}.jar"
  - "./material/target/s3material-assembly-${TRAVIS_TAG}.jar"
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  local_dir: docs/_book
  skip_cleanup: true
  target_branch: gh-pages
  github_token:
    secure: C+vg/B+z+fqEtWh80ovIRruknQgG1sL/OaM5E4xhy589uGi6MDHrAZS9YuZ5ViQFjfCGGo+XzS8Up86yYPMTr1F+kRTViO/pGZst1yA8xO5o7Ep1Xd+q2mItpAhGMPJU0q41G9gIg0epF0OyIuYeXcAXo5h0LsNBS6PAQQEfpJQ=
  email: manoj@indix.com
  name: Manoj
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: HQdcZwqDY9+vGW7N9YZ2tFeU50SgqrWEQefI/injWVcndkAL7U/TFOoFvyOdxPZA1sya3aKUyAfVVv7BzMdPUfas41LgYj+iSWAaidiwqrJMp3lkvvALoXId9IDrdWcbhqJ4F51dfO8ck6Jf0S9cXtXC8/dSunWJORdr9ycgkxs=
    on_success: change
    on_failure: always
